### ISSUE TITLE
fromMaybes and toList (and some 💭)

### ISSUE THREAD

**Issue by stoeffel** [joneshf/elm-these#3]
So, I was thinking about `These`. I have a usecase where I have two maybes. It would be nice to do the following:
```elm
These.fromMaybes maybeA maybeB -- fromMaybes : Maybe a -> Maybe b -> Maybe (These a b)
    |> Maybe.map (These.mapBoth viewA viewB)  -- viewA/B returning List (Html msg)
    |> Maybe.map (These.these identity identity (++))
    |> View.Extra.viewJust (Html.div [])
```

we could make it even nicer with adding `These.toList`
```elm
These.fromMaybes maybeA maybeB -- fromMaybes : Maybe a -> Maybe b -> Maybe (These a b)
    |> Maybe.map (These.mapBoth viewA viewB)  -- viewA/B returning Html msg!
    |> Maybe.map These.toList -- toList : These a a -> List a
    |> View.Extra.viewJust (Html.div [])
```

I was also wondering if there should be a different type that is `type MaybeThese = Nothing | This a | That b | These a b`
That would make that one example even nicer:

```elm
MaybeThese.fromMaybes maybeA maybeB -- fromMaybes : Maybe a -> Maybe b -> MaybeThese a b)
    |> MaybeThese.mapBoth viewA viewB)  -- viewA/B returning Html msg!
    |> MaybeThese.toList -- toList : MaybeThese a a -> List a
    |> viewIfElements (Html.div [])
```

I know at this point you can just do:
```elm
Maybe.Extra.values [ Maybe.map viewA maybeA, Maybe.map viewB maybeB ]
   |> viewIfElements (Html.div [])
```
Coming to a conclusion, maybe we shouldn't change anything 🤣 

All examples use the following `viewIfElements` (the one from view-extra doesn't pass the elements to the view function.
```elm
viewIfElements : (List a -> Html msg) -> List a -> Html msg
```
```

**Comment by joneshf** [comment]
> I was also wondering if there should be a different type that is `type MaybeThese = Nothing | This a | That b | These a b`

You know I love distinct types :). If you find it useful, add it!

> Coming to a conclusion, maybe we shouldn't change anything :rofl:

Up to you, I trust your judgement.

Speaking of, I always felt like a jerk for the way I responded in #1.

**Comment by stoeffel** [comment]
> You know I love distinct types :). If you find it useful, add it!

will think about it.

> Up to you, I trust your judgement.

❤️ 

> Speaking of, I always felt like a jerk for the way I responded in #1.

no worries at all!
