### ISSUE TITLE
Upgrade to v0.19

### ISSUE THREAD

**Issue by toastal** [joneshf/elm-these#4]
I'm not seeing anything that needs to change other than a version bump.

**Comment by joneshf** [comment]
This should be good now that #6 went in (it was #5 with style changes). Lemme know if there's more to do!

**Comment by toastal** [comment]
Hey! I'm happy to see it merged, but I still haven't seen a published release to the Elm packages. When you get time, can you do that last step (+ any version bumps necessary)?

**Comment by joneshf** [comment]
Oh geez. Totally missed that.

**Comment by joneshf** [comment]
This is published now as [1.2.1](https://package.elm-lang.org/packages/joneshf/elm-these/1.2.1/). Sorry it took so long. Lemme know if you need anything else.
